# explororation 13 : 아이유팬이 좋아할 만한 다른 아티스트 찾기

**루브릭 1. Abstractive 모델 구성을 위한 텍스트 전처리 단계가 체계적으로 진행되었다.**  
분석단계, 정제단계, 정규화와 불용어 제거, 데이터셋 분리, 인코딩 과정이 빠짐없이 체계적으로 진행되었다.

-> 잘 진행되었습니다.

**루브릭 2. 텍스트 요약모델이 성공적으로 학습되었음을 확인하였다.**  
모델 학습이 진행되면서 train loss와 validation loss가 감소하는 경향을 그래프를 통해 확인했으며, 실제 요약문에 있는 핵심 단어들이 요약 문장 안에 포함되었다.

-> 잘 진행되었습니다.

**루브릭 3. Extractive 요약을 시도해 보고 Abstractive 요약 결과과 함께 비교해 보았다.**  
두 요약 결과를 문법완성도 측면과 핵심단어 포함 측면으로 나누어 비교하고 분석 결과를 표로 정리하여 제시하였다.

-> 시간이 부족하여 하지 못했습니다.

***

## 목차

### 1. 사전작업

#### 1.1. 모듈 불러오기

#### 1.2. 데이터 불러오기

#### 1.3. 중복치 제거, 결측치 제거, 정규화, 불용어 제거

#### 1.4. 이상치 제거

#### 1.5. 데이터셋 구성

#### 1.6. 데이터 토큰화

##### 1.6.1. train set 토큰화

##### 1.6.2. test set 토큰화

##### 1.6.3. zero padding

### 2. 모델 구성 및 학습

#### 2.1. 기존의 seq2seq 모델

#### 2.2. attention이 추가된 seq2seq 모델

#### 2.3. 모델 학습

#### 2.4. 추론 모델 구성

### 3. 결과

### 4. 회고

***

## 13-2 데이터 탐색하기와 전처리

In [1]:
import pandas as pd
import os

fname = os.getenv('HOME') + '/aiffel/recommendata_iu/data/lastfm-dataset-360K/usersha1-artmbid-artname-plays.tsv'
col_names = ['user_id', 'artist_MBID', 'artist', 'play']   # 임의로 지정한 컬럼명
data = pd.read_csv(fname, sep='\t', names= col_names)      # sep='\t'로 주어야 tsv를 열 수 있습니다.  
data.head(10)

,user_id,artist_MBID,artist,play
0,00000c289a1829a808ac09c00daf10bc3c4e223b,3bd73256-3905-4f3a-97e2-8b341527f805,betty blowtorch,2137
1,00000c289a1829a808ac09c00daf10bc3c4e223b,f2fb0ff0-5679-42ec-a55c-15109ce6e320,die Ärzte,1099
2,00000c289a1829a808ac09c00daf10bc3c4e223b,b3ae82c2-e60b-4551-a76d-6620f1b456aa,melissa etheridge,897
3,00000c289a1829a808ac09c00daf10bc3c4e223b,3d6bbeb7-f90e-4d10-b440-e153c0d10b53,elvenking,717
4,00000c289a1829a808ac09c00daf10bc3c4e223b,bbd2ffd7-17f4-4506-8572-c1ea58c3f9a8,juliette & the licks,706
5,00000c289a1829a808ac09c00daf10bc3c4e223b,8bfac288-ccc5-448d-9573-c33ea2aa5c30,red hot chili peppers,691
6,00000c289a1829a808ac09c00daf10bc3c4e223b,6531c8b1-76ea-4141-b270-eb1ac5b41375,magica,545
7,00000c289a1829a808ac09c00daf10bc3c4e223b,21f3573f-10cf-44b3-aeaa-26cccd8448b5,the black dahlia murder,507
8,00000c289a1829a808ac09c00daf10bc3c4e223b,c5db90c4-580d-4f33-b364-fbaa5a3a58b5,the murmurs,424
9,00000c289a1829a808ac09c00daf10bc3c4e223b,0639533a-0402-40ba-b6e0-18b067198b73,lunachicks,403

In [2]:
len(data)

17535655

In [3]:
# 사용하는 컬럼만 남겨줍니다.
using_cols = ['user_id', 'artist', 'play']
data = data[using_cols]
data.head(10)

                                    user_id                   artist  play
0  00000c289a1829a808ac09c00daf10bc3c4e223b          betty blowtorch  2137
1  00000c289a1829a808ac09c00daf10bc3c4e223b                die Ärzte  1099
2  00000c289a1829a808ac09c00daf10bc3c4e223b        melissa etheridge   897
3  00000c289a1829a808ac09c00daf10bc3c4e223b                elvenking   717
4  00000c289a1829a808ac09c00daf10bc3c4e223b     juliette & the licks   706
5  00000c289a1829a808ac09c00daf10bc3c4e223b    red hot chili peppers   691
6  00000c289a1829a808ac09c00daf10bc3c4e223b                   magica   545
7  00000c289a1829a808ac09c00daf10bc3c4e223b  the black dahlia murder   507
8  00000c289a1829a808ac09c00daf10bc3c4e223b              the murmurs   424
9  00000c289a1829a808ac09c00daf10bc3c4e223b               lunachicks   403

In [ ]:
data['artist'] = data['artist'].str.lower() # 검색을 쉽게 하기 위해 아티스트 문자열을 소문자로 바꿔줍시다.
data.head(10)

In [ ]:
data[45:55]

In [ ]:
data.loc[data['user_id']== data.loc[0, 'user_id']][:10]

In [ ]:
len(data.loc[data['user_id']== data.loc[0, 'user_id']])

In [ ]:
data['play'].is_monotonic_decreasing

In [ ]:
# 유저 수
data['user_id'].nunique()

In [ ]:
# 아티스트 수
data['artist'].nunique()

In [ ]:
# 인기 많은 아티스트
artist_count = data.groupby('artist')['user_id'].count()
artist_count.sort_values(ascending=False).head(10)
# data.groupby('artist')['user_id'].count()[100:200]

In [ ]:
# 유저별 몇 명의 아티스트를 듣고 있는지에 대한 통계
# 각각의 유저들이 몇명의 아티스트들의 노래를 듣고 있는지
user_count = data.groupby('user_id')['artist'].count()
user_count.describe()

In [ ]:
# 유저별 play횟수 중앙값에 대한 통계
# 각각의 유저들의 플레이 횟수의 중앙값
user_median = data.groupby('user_id')['play'].median()
user_median.describe()

In [ ]:
# 본인이 좋아하시는 아티스트 데이터로 바꿔서 추가하셔도 됩니다! 단, 이름은 꼭 데이터셋에 있는 것과 동일하게 맞춰주세요. 
my_favorite = ['black eyed peas' , 'maroon5' ,'jason mraz' ,'coldplay' ,'beyoncé']

# 'zimin'이라는 user_id가 위 아티스트의 노래를 30회씩 들었다고 가정하겠습니다.
my_playlist = pd.DataFrame({'user_id': ['zimin']*5, 'artist': my_favorite, 'play':[30]*5})

if not data.isin({'user_id':['zimin']})['user_id'].any():  # user_id에 'zimin'이라는 데이터가 없다면
    data = data.append(my_playlist)                           # 위에 임의로 만든 my_favorite 데이터를 추가해 줍니다. 

data.tail(10)       # 잘 추가되었는지 확인해 봅시다.

In [ ]:
# 고유한 유저, 아티스트를 찾아내는 코드
user_unique = data['user_id'].unique()
artist_unique = data['artist'].unique()

# 유저, 아티스트 indexing 하는 코드 idx는 index의 약자입니다.
user_to_idx = {v:k for k,v in enumerate(user_unique)}
artist_to_idx = {v:k for k,v in enumerate(artist_unique)}

In [ ]:
print(user_unique)
print(len(user_unique))
print(artist_unique)
print(len(artist_unique))

In [ ]:
print(dict(list(user_to_idx.items())[:10]))
print(dict(list(artist_to_idx.items())[:10]))

In [ ]:
# 인덱싱이 잘 되었는지 확인해 봅니다. 
print(user_to_idx['zimin'])    # 358869명의 유저 중 마지막으로 추가된 유저이니 358868이 나와야 합니다. 
print(artist_to_idx['black eyed peas'])

In [ ]:
# indexing을 통해 데이터 컬럼 내 값을 바꾸는 코드
# dictionary 자료형의 get 함수는 https://wikidocs.net/16 을 참고하세요.

# user_to_idx.get을 통해 user_id 컬럼의 모든 값을 인덱싱한 Series를 구해 봅시다. 
# 혹시 정상적으로 인덱싱되지 않은 row가 있다면 인덱스가 NaN이 될 테니 dropna()로 제거합니다. 
temp_user_data = data['user_id'].map(user_to_idx.get).dropna()
if len(temp_user_data) == len(data):   # 모든 row가 정상적으로 인덱싱되었다면
    print('user_id column indexing OK!!')
    data['user_id'] = temp_user_data   # data['user_id']을 인덱싱된 Series로 교체해 줍니다. 
else:
    print('user_id column indexing Fail!!')

# artist_to_idx을 통해 artist 컬럼도 동일한 방식으로 인덱싱해 줍니다. 
temp_artist_data = data['artist'].map(artist_to_idx.get).dropna()
if len(temp_artist_data) == len(data):
    print('artist column indexing OK!!')
    data['artist'] = temp_artist_data
else:
    print('artist column indexing Fail!!')

data

## 13-4 사용자의 명시적/암묵적 평가

In [ ]:
# 1회만 play한 데이터의 비율을 보는 코드
only_one = data[data['play']<2]
one, all_data = len(only_one), len(data)
print(f'{one},{all_data}')
print(f'Ratio of only_one over all data is {one/all_data:.2%}')  # f-format에 대한 설명은 https://bit.ly/2DTLqYU

In [ ]:
data[data['play']<2]

한 번이라도 들었으면 선호한다고 판단한다.

많이 재생한 아티스트에 대해 가중치를 주어서 더 확실히 좋아한다고 판단한다.

## 13-5. Matrix Factorization(MF)

## 13-6. CSR(Compressed Sparse Row) Matrix

In [ ]:
# 실습 위에 설명보고 이해해서 만들어보기
from scipy.sparse import csr_matrix

num_user = data['user_id'].nunique()
num_artist = data['artist'].nunique()

csr_data = csr_matrix((data.play, (data.user_id, data.artist)), shape= (num_user, num_artist))
csr_data

In [ ]:
csr_data.shape

## 13-7. MF 모델 학습하기

In [ ]:
from implicit.als import AlternatingLeastSquares
import os
import numpy as np

# implicit 라이브러리에서 권장하고 있는 부분입니다. 학습 내용과는 무관합니다.
os.environ['OPENBLAS_NUM_THREADS']='1'
os.environ['KMP_DUPLICATE_LIB_OK'`]='True'
os.environ['MKL_NUM_THREADS']='1'

In [ ]:
# Implicit AlternatingLeastSquares 모델의 선언
als_model = AlternatingLeastSquares(factors=100, regularization=0.01, use_gpu=False, iterations=15, dtype=np.float32)

In [ ]:
# als 모델은 input으로 (item X user 꼴의 matrix를 받기 때문에 Transpose해줍니다.)
csr_data_transpose = csr_data.T
csr_data_transpose

In [ ]:
# 모델 훈련
als_model.fit(csr_data_transpose)